from tkinter import *
window = Tk()
window.title("Sample")
window.geometry("1000x1000")
label = Label(text = "This is text" ,fg = "white" ,bg = "Black" ,height = 20 ,width = 30)
button = Button(text = "This is a button", fg="white", bg = "black", height = 10,width = 10)
entry = Entry()
frame = Frame(master = window , relief = "raised" ,borderwidth = 5)
label.pack()
button.pack()
entry.pack()
frame.pack()
label1 = Label(master = frame, text="This is a frame")
label1.pack()
text = Text(fg="black", bg="white")
text.pack()
window.mainloop()